eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: 'http://discovery:8761/eureka/'
spring:
  cloud:
    gateway:
      routes:
      - id: PRODUCT-SERVICE
        predicates:
        - Path=/product/**
        uri: lb://PRODUCT-SERVICE
      - id: ORDER-SERVICE
        predicates:
        - Path=/settings/**
        uri: lb://ORDER-SERVICE
